Renamed from general. Set here all global stack settings
that are here for convenience, but can be set per role 
if fine grain desired.

Prefix by bb or bbg ? (bluebanquiseglobal ?)

### General settings file

bb_cluster_name: algoric

# Localisation
bb_time_zone: Europe/Brussels

## DNS
bb_domain_name: tumulus.local
bb_enable_fqdn: true << NEW, set all cluster as fqdn (impacts dhcp, set_hostname, dns, /etc/hosts, etc, but each role should be able to precedence for fine grained definition)

# Internal mechanisms
bb_icebergs_system: false  # Activate or deactivate icebergs topology system. Experimental.

# Services handling
<< Services handling must be fine grainable for each role
<< However, since precedence is tricky, must be made using dual j2 variables in roles
bb_enable_services: true  # Enable or disable services on startup (set to false when using high availability)
bb_start_services: true  # Handle start/restart of the services (set to false when using high availability)

<< Should be set in default of hosts_file role instead of here
# # /etc/hosts
# hosts_file:
#   range: all  # can be all (all hosts) or iceberg (iceberg only)
