### Network related settings

## List of logical networks
networks:

  ice1-1:
    subnet: 10.10.0.0
    prefix: 16
    ##netmask: 255.255.0.0  << should be now deduced from subnet and prefix
    ##broadcast: 10.10.255.255 << same
    dhcp_unknown_range: 10.10.254.1 10.10.254.254
    gateway: 10.10.2.1 << should disapear, and be replaced by gateway4 and gateway6
    dns4: << This one precedence services.dns4 if exist. dns_client should not exist anymore, all settings are handled by nmcli/networkd
    is_in_dhcp: true << should be true natively
    is_in_dns: true << should be true natively
    services:
      dns:
        - ip: 10.10.0.1
          host: dns1.cluster.local
        - ip: 10.10.0.2
          host: dns2.cluster.local    << This is an example

  interconnect-1:
    subnet: 10.20.0.0
    prefix: 16
