---
- name: "hostname █ Set {{ inventory_hostname }} hostname"
  ansible.builtin.hostname:
    name: "{{ set_hostname_fqdn | ternary( inventory_hostname + '.' + domain_name, inventory_hostname ) }}"
  tags:
    - identify
