---
- name: service █ Restart conman
  ansible.builtin.service:
    name: conman
    state: restarted
  when:
    - "'service' not in ansible_skip_tags"
    - (start_services | bool)

- name: systemd █ Reload systemd configuration
  ansible.builtin.systemd:
    daemon_reload: yes
