---
- name: registry █ Create local directory
  file:
    path: "{{ podman_local_registry_dir }}"
    state: directory
    owner: "{{ podman_local_registry_owner | default(root) }}"
    group: "{{ podman_local_registry_group | default(root) }}"
    mode: '0644'

- name: registry █ Check the path of the registry container
  stat:
    path: "{{ podman_registry_container_path }}"
  register: p

- name: registry █ Load local registry container
  command: "podman load -i {{ podman_registry_container_path }}"
  changed_when: false

- name: template █ Install registry service file
  template:
    src: registry.service.j2
    dest: /etc/systemd/system/registry.service
    owner: root
    group: root
    force: yes
    mode: 0655
  tags:
    - service

- name: systemd █ Reload systemd
  systemd:
    daemon_reload: yes
  tags:
    - service

- name: service █ Manage registry state
  service:
    name: registry
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
    state: "{{ (start_services | bool) | ternary('started', omit) }}"
  tags:
    - service
