---
# skip os repository as installation will have created
# /etc/zypp/repos.d/openSUSE-Leap-15.3-1.repo (or similar)

- name: set_fact ░ Set static baseurl prefix
  ansible.builtin.set_fact:
    baseurl_prefix:
      "http://{{ networks[j2_node_main_network]['services_ip']['repository_ip'] }}/repositories/\
      {{ ep_operating_system['repositories_environment'] | default('') }}/\
      {{ ep_operating_system['distribution'] }}/\
      {{ ep_operating_system['distribution_version'] | default(ep_operating_system['distribution_major_version']) }}/\
      {{ ansible_architecture }}/"

- name: zypper_repository █ Setting repositories
  community.general.zypper_repository:
    name: "{{ item.name | default(item) }}"
    description: "{{ item.name | default(item) }} gen by Ansible"
    repo: "{{ item.repo | default(baseurl_prefix + item.repo | default(item)) }}"
    disable_gpg_check: "{{ item.disable_gpg_check | default(omit) }}"
    auto_import_keys: "{{ item.disable_gpg_check | default(omit) }}"
    autorefresh: "{{ item.autorefresh | default(omit) }}"
    enabled: "{{ item.enabled | default(omit) }}"
    overwrite_multiple: "{{ item.overwrite_multiple | default(omit) }}"
    priority: "{{ item.priority | default(omit) }}"
    runrefresh: "{{ item.runrefresh | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ repositories }}"
  when: item != "os"

- name: lineinfile █ Disable delta RPMs
  ansible.builtin.lineinfile:
    path: /etc/zypp/zypp.conf
    insertafter: '# download.use_deltarpm = true'
    regexp: '^download.use_deltarpm ='
    line: 'download.use_deltarpm = false'
