---
- name: haproxy
  hosts: "mg_haproxys"
  roles:

    - role: set_hostname
      tags: set_hostname
    - role: custom_nic_nmcli
      tags: custom_nic_nmcli
    - role: hosts_file
      tags: hosts_file
    - role: dns_client
      tags: dns_client
    - role: time
      tags: time
      vars:
        time_profile: client