---
pxe_stack_role_version: 1.6.4

pxe_stack_supported_os:
  redhat:
    - major: 7
      distributions:
        - redhat
        - centos
    - major: 8
      distributions:
        - redhat
        - centos
        - oraclelinux
        - almalinux
        - rockylinux
    - major: 9
      distributions:
        - redhat
        - centosstream
        - oraclelinux
        - almalinux
        - rockylinux
  ubuntu:
    - major: 18
      distributions:
        - ubuntu
    - major: 20
      distributions:
        - ubuntu
    - major: 22
      distributions:
        - ubuntu
  dgxos:
    - major: 5
      distributions:
        - dgxos
  suse:
    - major: 15
      distributions:
        - opensuse

pxe_stack_redhat_automatic_partitioning: |
  clearpart --all --initlabel
  autopart --type=plain --fstype=ext4

pxe_stack_ubuntu_automatic_partitioning: " "

pxe_stack_suse_automatic_partitioning: |
  <partitioning config:type="list">
    <drive>
      <initialize config:type="boolean">true</initialize>
      <use>all</use>
      <partitions config:type="list">
        <partition>
          <filesystem config:type="symbol">ext4</filesystem>
          <mount>/</mount>
          <size>max</size>
        </partition>
        <partition>
          <filesystem config:type="symbol">ext4</filesystem>
          <mount>/boot</mount>
          <size>512MiB</size>
        </partition>
        <partition>
          <mount>swap</mount>
          <size>512MiB</size>
        </partition>
      </partitions>
    </drive>
  </partitioning>