- name: ufw █ "Add services to firewall"
  community.general.ufw:
    rule: allow
    port: "{{ log_server_port }}"
    proto: tcp
  when:
    - ep_firewall | default(false) | bool
  tags:
    - firewall
