- name: package █ Install clustershell package
  ansible.builtin.package:
    name: clustershell
    state: present
  tags:
    - package

- name: template █ Generate /etc/clustershell/groups.d/local.cfg
  ansible.builtin.template:
    src: local.cfg.j2
    dest: /etc/clustershell/groups.d/local.cfg
    owner: root
    group: root
    mode: 0644
  tags:
    - template
