---
- name: service █ Restart dns services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ dns_server_services_to_start }}"
  when:
    - "'service' not in ansible_skip_tags"
    - (start_services | bool)
