---
- name: authorized_key █ Add authorized key
  ansible.posix.authorized_key:
    user: root
    key: "{{ item }}"
    exclusive: no
    state: present
  with_items: "{{ authentication_ssh_keys }}"
