---
- name: command █ Reload connections
  command: nmcli con reload
  when: nic_nmcli_reload_connections

- name: command █ networkctl reload
  command: networkctl reload

- name: reboot █ Reboot system
  reboot:
    reboot_timeout: "{{ nic_nmcli_reboot_timeout }}"
  when:
    - nic_nmcli_allow_reboot
