---
- name: copy █ Copy /etc/netplan/01-netcfg.yaml
  template:
    src: netplan.yaml.j2
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: 0644
  notify:
    - command █ Netplan generate
    - command █ Netplan apply
  tags:
    - template

- name: file █ Ensure old netplan configuration is erased
  file:
    path: /etc/netplan/00-installer-config.yaml
    state: absent

- name: meta █ Run handlers
  meta: flush_handlers
