---
- name: template █ Render networkd NICs configuration
  ansible.builtin.template:
    src: networkd.j2
    dest: "/etc/systemd/network/{{ item.conn_name | default(item.interface) | string }}.network"
    owner: root
    group: root
    mode: 0644
  loop: "{{ network_interfaces }}"
  notify:
    - command █ networkctl reload
  tags:
    - template
    - identify

- name: meta █ Run handlers
  ansible.builtin.meta: flush_handlers
