---

# Global run on Ubuntu 20.04
# Using instance environment (no docker)

name: global ubuntu 20.04
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  global_run_ubuntu_2004:
    name: Global deployment on Ubuntu 20.04
    runs-on: ubuntu-20.04
    env:
      ANSIBLE_CONFIG: /var/lib/bluebanquise/ansible.cfg
      PY_COLORS: '1'
      ANSIBLE_FORCE_COLOR: '1'
    strategy:
      matrix:
        inventory: [light, standard, mi]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python environment
        uses: actions/setup-python@v1

      - name: Install packages
        run: pip3 install -r requirements.txt

      - name: Install collections
        run: ansible-galaxy collection install community.general

      - name: Prepare bluebanquise folder
        run: sudo mkdir /var/lib/bluebanquise; sudo chown -R $(id -u):$(id -g) /var/lib/bluebanquise; cp -a * /var/lib/bluebanquise;

      - name: Prepare bluebanquise environment
        run: |
          cp -a /var/lib/bluebanquise/resources/workflow/inventory_${{ matrix.inventory }} /var/lib/bluebanquise/inventory
          cp -a /var/lib/bluebanquise/resources/workflow/playbooks /var/lib/bluebanquise

      - name: Set dummy interface
        run: sudo modprobe -v dummy numdummies=2; sudo ip addr add 10.10.0.1/16 dev dummy0; ip a;

      - name: Role test - set_hostname
        run: ansible-playbook /var/lib/bluebanquise/playbooks/managements.yml --become --connection=local --limit mg1 -t set_hostname --diff
        continue-on-error: true

      - name: Role test - hosts_file
        run: ansible-playbook /var/lib/bluebanquise/playbooks/managements.yml --become --connection=local --limit mg1 -t hosts_file --diff
        continue-on-error: true

      - name: Role test - repositories_server
        run: ansible-playbook /var/lib/bluebanquise/playbooks/managements.yml --become --connection=local --limit mg1 -t repositories_server --diff
        continue-on-error: true

      - name: Role test - repositories_client
        run: ansible-playbook /var/lib/bluebanquise/playbooks/managements.yml --become --connection=local --limit mg1 -t repositories_client --diff
        continue-on-error: true

      - name: Role test - dhcp_server
        run: ansible-playbook /var/lib/bluebanquise/playbooks/managements.yml --become --connection=local --limit mg1 -t dhcp_server --diff
        continue-on-error: true

      - name: Role test - dns_server
        run: ansible-playbook /var/lib/bluebanquise/playbooks/managements.yml --become --connection=local --limit mg1 -t dns_server --diff
        continue-on-error: true

      - name: Role test - pxe_stack
        run: ansible-playbook /var/lib/bluebanquise/playbooks/managements.yml --become --connection=local --limit mg1 -t pxe_stack --diff --skip-tags package,need_package,service -e "bb_start_services=false"
        continue-on-error: true
