---
name: roles/grafana unit testing
on:
  push:
    branches:
      - main
    paths:
      - 'roles/grafana/**'
      - '.github/workflows/molecule-actions-roles-grafana.yml'
  pull_request:
    paths:
      - 'roles/grafana/**'
      - '.github/workflows/molecule-actions-roles-grafana.yml'

jobs:
  molecule_test:
    name: ${{ matrix.distro }} - molecule test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6','3.8','3.9','3.10']
        distro:
          - centos7
          - centos8
          - rockylinux8
          - ubuntu1804
          - ubuntu2004
          - ubuntu2204

    env:
      MOLECULE_DISTRO: ${{ matrix.distro }}
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python environment
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install packages
        run: |
          pip install tox
      - name: Run molecule test for roles/grafana
        run: |
          cd roles/grafana && tox